version: '3.3'
services:
  # db:
  #   image: mysql:5.7
  #   restart: always
  #   environment:
  #     MYSQL_DATABASE: 'coolDB'
  #     # Password for root access
  #     MYSQL_ROOT_PASSWORD: 'pw'
  #   ports:
  #     # <Port exposed> : < MySQL Port running inside container>
  #     - '3306:3306'
  #     # Where our data will be persisted
  #   volumes:
  #     - my-db:/var/lib/mysql

  trintel:
    image: b3zz/trintel:1.4.0
    # depends_on:
    #   - db
    ports:
      - '8082:8080'
    restart: always
    volumes:
      - trintel-database:/trintel-database

  trintel-v2:
    image: b3zz/trintel:1.4.0
    ports:
      - '8083:8080'
    restart: always
    volumes:
      - trintel-database-v2:/trintel-database

  filebeat:
    image: "docker.elastic.co/beats/filebeat:7.2.0"
    user: root
    volumes:
      - /root/trintel/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock

#  logstash:
#    image: docker.elastic.co/logstash/logstash:7.2.0
#    volumes:
#      - /root/trintel/pipeline:/usr/share/logstash/pipeline
#    ports:
#      - 5044:5044

# Names our volume
volumes:
  trintel-database:
  trintel-database-v2:
