filebeat.autodiscover:
  providers:
    - type: docker
      labels.dedot: true
      templates:
        - condition:
            contains:
              docker.container.image: b3zz/trintel
          config:
            - type: container
              format: docker
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log
#              exclude_lines: ["^\\s+[\\-`('.|_]"]  # drop asciiart lines
              processors:
                - decode_json_fields:
#                    when.equals:
#                      docker.container.labels.decode_log_event_to_json_object: "true"
                    fields: ["message"]
                    target: ""
                    overwrite_keys: true

processors:
- add_docker_metadata:
    host: "unix:///var/run/docker.sock"

#- decode_json_fields:
#    fields: ["message"]
#    target: "json"
#    overwrite_keys: true

output.logstash:
  hosts: ["dev.zeppel.eu:5044"]
  loadbalance: true
  ssl.enabled: false

logging.json: true
logging.metrics.enabled: false