# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  spring.mail.host: ${{ vars.MAIL_HOST }}
  spring.mail.port: ${{ vars.MAIL_PORT }}
  spring.mail.username: ${{ vars.MAIL_USERNAME }}
  spring.mail.password: ${{ secrets.MAIL_PASSWORD }}
  spring.mail.properties.mail.smtp.auth: ${{ vars.MAIL_SMTP }}
  spring.mail.properties.mail.smtp.starttls.enable: ${{ vars.MAIL_SMTP_TLS }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
    - name: Save PMD report
      uses: actions/upload-artifact@v2
      with:
        name: PMD Report
        path: build/reports/pmd/*
